### ISSUE TITLE
Add Support For Async

### ISSUE THREAD

**Issue by jakejgordon** [RIDGIDSoftwareSolutions/Universal-Analytics-For-DotNet#2]
Something like tracking an event really should be async. Add support for this.

**Comment by david2h1** [comment]
Take a look at #6

**Comment by jakejgordon** [comment]
Code is merged and deployed! I've updated the #7 issue to mention that we need to provide some async examples right in code. Thanks!

PS: What's your twitter handle so I can give you a shout-out for helping?

**Comment by jakejgordon** [comment]
FYI, I also reverted back to 4.5.1 since I don't think there was any need to go up to 4.6.
