### ISSUE TITLE
Add support for optional UserId

### ISSUE THREAD

**Issue by jakejgordon** [RIDGIDSoftwareSolutions/Universal-Analytics-For-DotNet#5]
Allow the client ID to be optional instead of required, as it states in the documentation here: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid

**Comment by yaronguez** [comment]
Was this feature ever added?

**Comment by jakejgordon** [comment]
Hi @yaronguez I think the purpose of this issue is to make the CID optional instead of required as it states here: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid -- which I don't think was ever done. Does that answer your question?

**Comment by yaronguez** [comment]
Yes, if the CID was optional than the UID could provided instead. You're
saying that this isn't possible with this library?

Yaron Guez
Software Architect
(781) 249-4709

**Comment by jakejgordon** [comment]
Sorry for the delayed response. Right now it does not accept userId. You can add support via a Pull Request or I could try to take a stab at it in the next week or so -- it should be pretty easy. Let me know.

**Comment by yaronguez** [comment]
Thanks! Let me know if you get a chance to add this feature in the next
week or so.

Yaron Guez
Software Architect
(781) 249-4709

**Comment by yaronguez** [comment]
Hi @jakejgordon, did you ever find the time to add that feature?

**Comment by jakejgordon** [comment]
Sorry Yaron -- I actually did not. I'm really sorry I forgot to response. Realistically, I probably won't get to this for another couple of weeks. If this is a major problem or a deal-breaker for you let me know and I'll see what I can do.

**Comment by yaronguez** [comment]
No worries, Jake. It's an open source project after all. I'll just call the Analytics API directly using the HttpClient class.

**Comment by cogree** [comment]
This is currently supported in version 1.4.4 of the Nuget package. Closing.
